config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :users do
    resources :contacts, only: :index
    resources :contact_logs, only: :index
    resources :contact_files, only: [:index, :new, :create]
    get "import_contacts", to: "contacts#import_contacts"
    post 'import_contacts', to: 'contacts#create'
  end

  root to: 'users/contacts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
# frozen_string_literal: true
require 'credit_card_validations/string'

class Contact < ApplicationRecord
  belongs_to :user

  validates :email, :name, :birth_date, :phone, :address, :credit_card, :franchise, :user, presence: true
  validates :email, uniqueness: { scope: :user_id }
  validates :name, format: { with: /\A[A-Za-z0-9-]*\z/ }
  validate :phone_format
  validate :date_format
  validate :credit_card_format

  after_initialize :init_franchise
  attr_encrypted :credit_card, key: Base64.decode64(Rails.application.credentials.encryption_key)

  private

  def phone_format
    return unless phone

    format_1 = /\A[(][+][0-9]{2}[)] [0-9]{3} [0-9]{3} [0-9]{2} [0-9]{2}\z/
    format_2 = /\A[(][+][0-9]{2}[)] [0-9]{3}-[0-9]{3}-[0-9]{2}-[0-9]{2}\z/

    errors.add(:phone, :invalid, message: "invalid phone format") unless phone=~format_1 || phone=~format_2
  end

  def date_format
    return unless birth_date

    basic_format = Time.parse(birth_date_before_type_cast).strftime('%Y%m%d')
    extend_format = Time.parse(birth_date_before_type_cast).strftime('%F')

    errors.add(:birth_date, :invalid, message: "invalid date format") unless basic_format == birth_date_before_type_cast || extend_format == birth_date_before_type_cast
  end

  def credit_card_format
    return if valid_credit_card?

    errors.add(:credit_card, :invalid, message: "invalid credit card format")
  end

  def init_franchise
    return unless valid_credit_card?

    self.franchise = credit_card.credit_card_brand_name
  end

  def valid_credit_card?
    return unless credit_card

    credit_card.credit_card_brand_name
  end
end

app/models/contact_file.rb
# frozen_string_literal: true

class ContactFile < ApplicationRecord
  include AASM
  belongs_to :user
  after_create :import_contacts

  aasm :state do
    state :on_hold, initial: true
    state :processing, :failed, :finished

    event :start_process do
      transitions from: [:on_hold], to: :processing
    end

    event :fail_process do
      transitions from: [:processing], to: :failed
    end

    event :finish_process do
      transitions from: [:processing], to: :finished
    end
  end

  def import_contacts
    ContactFileImporterWorker.perform_async(self.id)
  end
end

app/models/contact_log.rb
# frozen_string_literal: true

class ContactLog < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :contacts
  has_many :contact_logs
  has_many :contact_files

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/users/contact_files_controller.rb
class Users::ContactFilesController < ApplicationController
  before_action :authenticate_user!

  def index
    @pagy, @contact_files = pagy(current_user.contact_files)
  end

  def new
    @contact_file = current_user.contact_files.new
  end

  def create
    @contact_file = current_user.contact_files.new(contact_file_params)

    if @contact_file.save
      redirect_to users_contact_files_path, notice: "The file was uploaded successfully"
    else
      redirect_to new_users_contact_file_path, alert: "Ups, something wrong. Try again."
    end
  end

  def contact_file_params
    file = params[:contact_file][:contacts_file]
    {
      filename: file.original_filename,
      content: file.read,
      match_columns: params[:contact_file][:match_columns].as_json
    }
  end
end

app/controllers/users/contact_logs_controller.rb
class Users::ContactLogsController < ApplicationController
  before_action :authenticate_user!

  def index
    @pagy, @contact_logs = pagy(current_user.contact_logs)
  end
end

app/controllers/users/contacts_controller.rb
class Users::ContactsController < ApplicationController
  before_action :authenticate_user!

  def index
    @pagy, @contacts = pagy(current_user.contacts.decorate)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :username])
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactImporterKoombea</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/flash'%>
    <ul>
      <li><a href="<%= users_contacts_path %>">Contacts</a></li>
      <li><a href="<%= users_contact_logs_path %>">Contact Logs</a></li>
      <li><a href="<%= users_contact_files_path %>">Contact Files</a></li>
      <li><a href="<%= new_users_contact_file_path %>">Import Contact</a></li>
    </ul>

    <%= yield %>
  </body>
</html>

app/views/shared/_flash.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/users/contact_files/index.html.erb
<h2>Contact Files</h2>

<table>
  <tr>
    <th>Filename</th>
    <th>Upload at</th>
    <th>State</th>
  </tr>
  <% @contact_files.each do |contact_file| %>
    <tr>
      <td><%= contact_file.filename %></td>
      <td><%= contact_file.created_at %></td>
      <td><%= contact_file.state %></td>
    </tr>
  <% end %>

  <%== pagy_nav(@pagy) %>
</table>

app/views/users/contact_files/new.html.erb
<h2>Import Contacts</h2>

<p>Please fill the fields according with the names that you use in your contacts file.
  i.e: Contact Name -> Contacts, the column in my csv file that contains the contact name is Contacts, so,
  in the filed Name you need to put Contacts in order to match it</p>
<%= form_with model: [:users, @contact_file] do |form| %>

  <p> In your csv file, what names you assign to the following values:</p>
  <%= form.fields_for :match_columns do |header| %>
    <div>
      <%= header.label :contact_name %>
      <%= header.text_field :name, required: true %>
    </div>
    <div>
      <%= header.label :contact_birth_date %>
      <%= header.text_field :birth_date, required: true %>
    </div>
    <div>
      <%= header.label :contact_phone %>
      <%= header.text_field :phone, required: true %>
    </div>
    <div>
      <%= header.label :contact_address %>
      <%= header.text_field :address, required: true %>
    </div>
    <div>
      <%= header.label :contact_credit_card %>
      <%= header.text_field :credit_card, required: true %>
    </div>
    <div>
      <%= header.label :contact_franchise %>
      <%= header.text_field :franchise, required: true %>
    </div>
    <div>
      <%= header.label :contact_email %>
      <%= header.text_field :email, required: true %>
    </div>
  <% end %>

  <%= form.file_field :contacts_file %>

  <%= form.submit "Import contacts" %>
<% end %>

app/views/users/contact_logs/index.html.erb
<h2>Contacts Logs</h2>

<table>
  <tr>
    <th>Contact Details</th>
    <th>Errors</th>
  </tr>
  <% @contact_logs.each do |contact| %>
    <tr>
      <td><%= contact.contact_details %></td>
      <td><%= contact.errors_details %></td>
    </tr>
  <% end %>

  <%== pagy_nav(@pagy) %>
</table>

app/views/users/contacts/index.html.erb
<h2>Contacts list</h2>

<table>
  <tr>
    <th>Name</th>
    <th>Date of Birth</th>
    <th>Phone</th>
    <th>Address</th>
    <th>Credit Card</th>
    <th>Franchise</th>
    <th>Email</th>
  </tr>
  <% @contacts.each do |contact| %>
    <tr>
      <td><%= contact.name %></td>
      <td><%= contact.birth_date %></td>
      <td><%= contact.phone %></td>
      <td><%= contact.address %></td>
      <td><%= contact.credit_card %></td>
      <td><%= contact.franchise %></td>
      <td><%= contact.email %></td>
    </tr>
  <% end %>

  <%== pagy_nav(@pagy) %>
</table>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>